branches: [ 'main' ]

repositoryUrl: 'https://girt.ir/sahand.k/semantic-release'

plugins: [
  '@semantic-release/commit-analyzer',
  [
    '@semantic-release/release-notes-generator',
    {
      presetConfig: {
        issueUrlFormat: 'https://app.clickup.com/t/{{id}}'
      }
    }
  ],
  '@semantic-release/gitlab']


debug: true
